version: '3'
services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - mongo
    volumes:
      - .:/myproject
    ports:
      - '8000:8000'

  mongo:
    image: mongo:3
    container_name: mongo
    volumes:
      - ~/data/mongo:/data/db
    ports:
      - '27017:27017'
